package controller;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Owner
 */
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.*;
import controller.TournamentSoftware;
import model.Participant;

public class Driver extends javax.swing.JFrame {

    TournamentSoftware ts;
    ListDisplayAndEntry listDisplayAndEntry;
    
    
    /**
     * Creates new form TournamentSoftware
     */
    

    public Driver() {
        initComponents();
        ts = new TournamentSoftware("badminton.txt");
        listDisplayAndEntry = new ListDisplayAndEntry(ts.getAllParticipants(), jPanel1, participantDialog);
        
        ts.displayAllEvents();
        ts.displayMismatchedList();
        ts.displayNeedList();
        ts.displayAllDraws();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        participantDialog = new javax.swing.JDialog();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        clubField = new javax.swing.JTextField();
        clubLabel = new javax.swing.JLabel();
        groupLabel = new javax.swing.JLabel();
        groupField = new javax.swing.JTextField();
        tShirtSizeLabel = new javax.swing.JLabel();
        tShirtSizeField = new javax.swing.JTextField();
        mixedLabel = new javax.swing.JLabel();
        eventDLabel = new javax.swing.JLabel();
        doublesLabel = new javax.swing.JLabel();
        singlesLabel = new javax.swing.JLabel();
        eventALabel = new javax.swing.JLabel();
        eventBLabel = new javax.swing.JLabel();
        eventCLabel = new javax.swing.JLabel();
        awsCB = new javax.swing.JCheckBox();
        amsCB = new javax.swing.JCheckBox();
        bmsCB = new javax.swing.JCheckBox();
        bwsCB = new javax.swing.JCheckBox();
        cmsCB = new javax.swing.JCheckBox();
        cwsCB = new javax.swing.JCheckBox();
        dmsCB = new javax.swing.JCheckBox();
        dwsCB = new javax.swing.JCheckBox();
        awdCB = new javax.swing.JCheckBox();
        amdCB = new javax.swing.JCheckBox();
        bmdCB = new javax.swing.JCheckBox();
        bwdCB = new javax.swing.JCheckBox();
        cmdCB = new javax.swing.JCheckBox();
        cwdCB = new javax.swing.JCheckBox();
        dmdCB = new javax.swing.JCheckBox();
        dwdCB = new javax.swing.JCheckBox();
        amxCB = new javax.swing.JCheckBox();
        bmxCB = new javax.swing.JCheckBox();
        cmxCB = new javax.swing.JCheckBox();
        dmxCB = new javax.swing.JCheckBox();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        tShirtCB = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        participantDialog.getContentPane().setLayout(null);

        firstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstNameLabel.setText("First:");
        participantDialog.getContentPane().add(firstNameLabel);
        firstNameLabel.setBounds(10, 50, 40, 20);
        participantDialog.getContentPane().add(firstNameField);
        firstNameField.setBounds(50, 50, 140, 20);

        lastNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNameLabel.setText("Last:");
        participantDialog.getContentPane().add(lastNameLabel);
        lastNameLabel.setBounds(190, 50, 40, 20);
        participantDialog.getContentPane().add(lastNameField);
        lastNameField.setBounds(230, 50, 140, 20);

        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        genderLabel.setText("Gender:");
        participantDialog.getContentPane().add(genderLabel);
        genderLabel.setBounds(370, 50, 50, 20);
        participantDialog.getContentPane().add(genderField);
        genderField.setBounds(420, 50, 30, 20);

        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("Email:");
        participantDialog.getContentPane().add(emailLabel);
        emailLabel.setBounds(10, 80, 40, 20);
        participantDialog.getContentPane().add(emailField);
        emailField.setBounds(50, 80, 140, 20);
        participantDialog.getContentPane().add(phoneField);
        phoneField.setBounds(410, 80, 120, 20);

        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phoneLabel.setText("Phone:");
        participantDialog.getContentPane().add(phoneLabel);
        phoneLabel.setBounds(370, 80, 40, 20);
        participantDialog.getContentPane().add(clubField);
        clubField.setBounds(230, 80, 140, 20);

        clubLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clubLabel.setText("Club:");
        participantDialog.getContentPane().add(clubLabel);
        clubLabel.setBounds(190, 80, 40, 20);

        groupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        groupLabel.setText("Group:");
        participantDialog.getContentPane().add(groupLabel);
        groupLabel.setBounds(10, 110, 40, 20);
        participantDialog.getContentPane().add(groupField);
        groupField.setBounds(50, 110, 140, 20);

        tShirtSizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tShirtSizeLabel.setText("T-shirt Size:");
        tShirtSizeLabel.setEnabled(false);
        participantDialog.getContentPane().add(tShirtSizeLabel);
        tShirtSizeLabel.setBounds(260, 110, 70, 20);

        tShirtSizeField.setEnabled(false);
        participantDialog.getContentPane().add(tShirtSizeField);
        tShirtSizeField.setBounds(330, 110, 30, 20);

        mixedLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mixedLabel.setText("Mixed");
        participantDialog.getContentPane().add(mixedLabel);
        mixedLabel.setBounds(10, 250, 60, 30);

        eventDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventDLabel.setText("D");
        participantDialog.getContentPane().add(eventDLabel);
        eventDLabel.setBounds(340, 160, 60, 30);

        doublesLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        doublesLabel.setText("Doubles");
        participantDialog.getContentPane().add(doublesLabel);
        doublesLabel.setBounds(10, 220, 60, 30);

        singlesLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        singlesLabel.setText("Singles");
        participantDialog.getContentPane().add(singlesLabel);
        singlesLabel.setBounds(10, 190, 60, 30);

        eventALabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventALabel.setText("A");
        participantDialog.getContentPane().add(eventALabel);
        eventALabel.setBounds(100, 160, 60, 30);

        eventBLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventBLabel.setText("B");
        participantDialog.getContentPane().add(eventBLabel);
        eventBLabel.setBounds(180, 160, 60, 30);

        eventCLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventCLabel.setText("C");
        participantDialog.getContentPane().add(eventCLabel);
        eventCLabel.setBounds(260, 160, 60, 30);

        awsCB.setText("W");
        participantDialog.getContentPane().add(awsCB);
        awsCB.setBounds(130, 190, 40, 23);

        amsCB.setText("M");
        participantDialog.getContentPane().add(amsCB);
        amsCB.setBounds(100, 190, 33, 23);

        bmsCB.setText("M");
        participantDialog.getContentPane().add(bmsCB);
        bmsCB.setBounds(180, 190, 33, 23);

        bwsCB.setText("W");
        participantDialog.getContentPane().add(bwsCB);
        bwsCB.setBounds(210, 190, 40, 23);

        cmsCB.setText("M");
        participantDialog.getContentPane().add(cmsCB);
        cmsCB.setBounds(260, 190, 33, 23);

        cwsCB.setText("W");
        participantDialog.getContentPane().add(cwsCB);
        cwsCB.setBounds(290, 190, 40, 23);

        dmsCB.setText("M");
        participantDialog.getContentPane().add(dmsCB);
        dmsCB.setBounds(340, 190, 33, 23);

        dwsCB.setText("W");
        participantDialog.getContentPane().add(dwsCB);
        dwsCB.setBounds(370, 190, 40, 23);

        awdCB.setText("W");
        participantDialog.getContentPane().add(awdCB);
        awdCB.setBounds(130, 220, 40, 23);

        amdCB.setText("M");
        participantDialog.getContentPane().add(amdCB);
        amdCB.setBounds(100, 220, 33, 23);

        bmdCB.setText("M");
        participantDialog.getContentPane().add(bmdCB);
        bmdCB.setBounds(180, 220, 33, 23);

        bwdCB.setText("W");
        participantDialog.getContentPane().add(bwdCB);
        bwdCB.setBounds(210, 220, 40, 23);

        cmdCB.setText("M");
        participantDialog.getContentPane().add(cmdCB);
        cmdCB.setBounds(260, 220, 33, 23);

        cwdCB.setText("W");
        participantDialog.getContentPane().add(cwdCB);
        cwdCB.setBounds(290, 220, 40, 23);

        dmdCB.setText("M");
        participantDialog.getContentPane().add(dmdCB);
        dmdCB.setBounds(340, 220, 33, 23);

        dwdCB.setText("W");
        participantDialog.getContentPane().add(dwdCB);
        dwdCB.setBounds(370, 220, 40, 23);
        participantDialog.getContentPane().add(amxCB);
        amxCB.setBounds(120, 250, 33, 23);
        participantDialog.getContentPane().add(bmxCB);
        bmxCB.setBounds(200, 250, 33, 23);
        participantDialog.getContentPane().add(cmxCB);
        cmxCB.setBounds(280, 250, 33, 23);
        participantDialog.getContentPane().add(dmxCB);
        dmxCB.setBounds(360, 250, 33, 23);

        updateButton.setText("Update");
        participantDialog.getContentPane().add(updateButton);
        updateButton.setBounds(540, 290, 90, 23);

        cancelButton.setText("Cancel");
        participantDialog.getContentPane().add(cancelButton);
        cancelButton.setBounds(440, 290, 90, 23);

        tShirtCB.setText("T-shirt?");
        tShirtCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tShirtCBActionPerformed(evt);
            }
        });
        participantDialog.getContentPane().add(tShirtCB);
        tShirtCB.setBounds(200, 110, 70, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Participant Info");
        participantDialog.getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 150, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(835, 578));
        setName("frame");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Participants");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 120, 30);

        jTabbedPane1.addTab("General", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Round32.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setBounds(0, 50, 660, 380);
        jLayeredPane1.add(jLabel1, new Integer(1));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jScrollPane1.setBounds(690, 50, 110, 380);
        jLayeredPane1.add(jScrollPane1, new Integer(1));

        jPanel2.add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("tab3", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1000, 750);

        jMenu1.setText("File");

        jMenu3.setText("Create...");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("from Text File");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tShirtCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tShirtCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tShirtCBActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) throws IOException {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Driver().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox amdCB;
    private javax.swing.JCheckBox amsCB;
    private javax.swing.JCheckBox amxCB;
    private javax.swing.JCheckBox awdCB;
    private javax.swing.JCheckBox awsCB;
    private javax.swing.JCheckBox bmdCB;
    private javax.swing.JCheckBox bmsCB;
    private javax.swing.JCheckBox bmxCB;
    private javax.swing.JCheckBox bwdCB;
    private javax.swing.JCheckBox bwsCB;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField clubField;
    private javax.swing.JLabel clubLabel;
    private javax.swing.JCheckBox cmdCB;
    private javax.swing.JCheckBox cmsCB;
    private javax.swing.JCheckBox cmxCB;
    private javax.swing.JCheckBox cwdCB;
    private javax.swing.JCheckBox cwsCB;
    private javax.swing.JCheckBox dmdCB;
    private javax.swing.JCheckBox dmsCB;
    private javax.swing.JCheckBox dmxCB;
    private javax.swing.JLabel doublesLabel;
    private javax.swing.JCheckBox dwdCB;
    private javax.swing.JCheckBox dwsCB;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel eventALabel;
    private javax.swing.JLabel eventBLabel;
    private javax.swing.JLabel eventCLabel;
    private javax.swing.JLabel eventDLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField genderField;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField groupField;
    private javax.swing.JLabel groupLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel mixedLabel;
    private javax.swing.JDialog participantDialog;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel singlesLabel;
    private javax.swing.JCheckBox tShirtCB;
    private javax.swing.JTextField tShirtSizeField;
    private javax.swing.JLabel tShirtSizeLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
